name: 'Prepare PNPM'
description: 'Set up Node.js & PNPM and install dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    default: '16.x'
    required: false
  pnpm-version:
    description: 'PNPM version'
    default: 7.0.0
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set up PNPM
      uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i -r
      shell: bash
