[tool.poetry]
name = "hahnpro-flow-sdk"
version = "0.1.4"
description = ""
authors = ["timoklingenhoefer <timo.klingenhoefer@web.de>"]
readme = "README.md"
packages = [{include = "hahnpro_flow_sdk"}]

[tool.poetry.dependencies]
python = "^3.7"
aio-pika = "^8.2.2"
typing-extensions = "^4.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
