stages:
  - test

commit-messages:
  stage: test
  image: outillage/commitsar:0.15.0
  script:
    - commitsar
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_ID

.pnpm:
  image: node:lts
  before_script:
    - npm install -g pnpm
    - pnpm install

test-cli:
  extends: .pnpm
  stage: test
  script:
    - pnpm test packages/cli
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - packages/cli/**/*
        - package.json

test-sdk:
  image: registry.gitlab.com/hahnpro/hpc/flow-executor-base:14
  stage: test
  before_script:
    - npm install -g pnpm
    - pnpm install
  services:
    - rabbitmq:3
  script:
    - pnpm test packages/sdk -- --testPathIgnorePatterns api.spec.ts http.service.spec.ts sidrive.spec.ts
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - packages/sdk/**/*
        - package.json
  tags:
    - multi-core
