[tool.poetry]
name = "hahnpro-hpc-api"
version = "0.1.1"
description = ""
authors = ["timoklingenhoefer <timo.klingenhoefer@web.de>"]
readme = "README.md"
packages = [{include = "hpc_api"}]

[tool.poetry.dependencies]
python = "^3.7"
Authlib = "^1.1.0"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
