[tool.poetry]
name = "hahnpro-flow-sdk"
version = "0.1.0"
description = ""
authors = ["timoklingenhoefer <timo.klingenhoefer@web.de>"]
readme = "README.md"
packages = [{include = "flow_sdk"}]

[tool.poetry.dependencies]
python = "^3.7"
aio-pika = "^8.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
