name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm
      - name: Activate Post Build Hooks
        run: pnpm config set enable-pre-post-scripts true
      - name: Build API & SDK
        run: pnpm build --filter @hahnpro/hpc-api --filter @hahnpro/flow-sdk
      - name: Create Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          publish: pnpm -r publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
