name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 100
      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm
      - name: Activate Post Build Hooks
        run: pnpm config set enable-pre-post-scripts true
      - name: Build SDK
        run: pnpm --filter @hahnpro/flow-sdk build
      - name: Create Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          publish: pnpm -r publish
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
