name: Validate

on:
  pull_request:
    branches: [main]

jobs:
  validate-commits:
    name: Validate Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Validate Commits
        uses: wagoid/commitlint-github-action@v6
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm
      - name: Lint
        run: pnpm -r lint
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm
      - name: Audit
        run: pnpx audit-ci --high --skip-dev --allowlist GHSA-v6h2-p8h4-qcjw
