name: Validate Pull Request

on:
  pull_request_target:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v4.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
